spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://8.130.130.65:3306/mall?characterEncoding=utf-8
      username: root
      password: admin123
  redis:
    port: 6379
    host: 8.130.130.65
    database: 0
    password: 123456


mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.lb.mall.entity

redisson:
  addr:
    singleAddr:
      host: redis://8.130.130.65:6379
      password: 123456
      database: 0
