server:
    port: 8888
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/WoodLike0207/mall-config.git
                    search-paths: files
                    skip-ssl-validation: true


eureka:
    client:
        service-url:
            defaultZone: http://zhangsan:123456@localhost:8761/eureka